# Generated by Django 4.2.2 on 2023-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_experience_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_time',
            field=models.DateField(blank=True, default='', null=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_time',
            field=models.DateField(blank=True, default='', null=True, verbose_name='%d/%m/%Y'),
        ),
    ]
