# Generated by Django 4.2.2 on 2023-06-12 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_experience_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course_details',
            field=models.TextField(default=datetime.datetime(2023, 6, 12, 8, 47, 37, 458113, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_time',
            field=models.CharField(default=datetime.datetime(2023, 6, 12, 8, 47, 46, 47449, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='organisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='organisation_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2023, 6, 12, 8, 47, 53, 663575, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
