# Generated by Django 4.2.2 on 2023-06-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_education_course_details_education_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_time',
        ),
    ]
