# Generated by Django 4.2.2 on 2023-06-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_education_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
    ]
